### ISSUE TITLE
A/An grammatical error

### ISSUE THREAD

**Issue by KoolKidz112** [KoolKidz112/blankcheque#2]
Filled-in blanks starting with vowels that follow a/an can result in grammatical errors like this:
```js
{w:WordType.PRNOUN},
" (born ",
{w:WordType.TIME},
") is an ",
{w:WordType.ADJ},
" podcaster"
```
Where an adjective such as "crazy" can cause the text to render as "an crazy" which is Crazy Shtewpid.

**Comment by pixdoet** [comment]
'"An" grammatical error' is wrong because "grammatical" starts with "g" and it's not a vowel.

**Comment by KoolKidz112** [comment]
The "a/an" in the title is meant to be used as a Noun, good one, not as preposition
